### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [ronanren/Covid19bot#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame  http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/CA3YYE
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by ronanren** [comment]
Hello, 
Yes, i will keeping the dataset up-to-date ;) thank you for your trust

**Comment by k-goncharova** [comment]
Ronan, thank you for your response and willingness to contribute. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the necessary permissions for editing your dataset. It would be also helpful, if you could add metadata (description, keywords) to your dataset in Dataverse.
